version: "3.2"
services:
  app:
    build:
      args:
        WEB_USER_ID: 1000 #local user id
        WEB_USER_NAME: developer #any user name
  nginx:
    build:
      args:
        WEB_USER_ID: 1000
        WEB_USER_NAME: developer
    ports:
    - 8001:80
