version: "3.2"
services:
  app:
    build:
      context: ./app
    volumes:
    - ./app:/var/www/app
    - ./app/php_opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    - sock:/sock
    working_dir: /var/www/app
  nginx:
    build:
      context: ./nginx
    volumes:
    - ./app/public:/var/www/app/public
    - sock:/sock
  redis:
    image: "redis"
volumes:
  sock:
